#!/bin/sh

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#0d8d09ff'  # default
T='#ffffffff'  # text
W='#c70303ff'  # wrong
V='#ffffffff'  # verifying

/usr/bin/i3lock \
--insidever-color=$C   \
--ringver-color=$V     \
\
--insidewrong-color=$C \
--ringwrong-color=$W   \
\
--inside-color=$B      \
--ring-color=$B        \
--line-color=$B        \
--separator-color=$D   \
\
--verif-color=$T        \
--wrong-color=$T        \
--time-color=$T        \
--date-color=$T        \
--layout-color=$T      \
--keyhl-color=$T       \
--bshl-color=$W        \
\
--screen 1            \
--blur 5              \
--clock               \
#--indicator           \
--time-str="%H:%M:%S"  \
--date-str="%A, %m %Y" \
#--keylayout 1         \
